config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,controllers: {
    Registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :contacts, only:[:new,:create] do
   collection do
     post :confirm
   end
  end

  resources :blogs do
    resources :comments
      post :confirm,on: :collection
  end

  resources :users,only:[:index,:show]

  resources :relationships,only:[:create,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at:"/letter_opener"
  end

  resources :poems,only:[:index,:show]

  resources :conversations do
    resources :messages
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base

    validates:title,presence:true
    validates:content,presence:true
    belongs_to :user
    has_many :comments,dependent: :destroy

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  has_many :notifications,dependent: :destroy
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    
    validates:name,presence:true
    validates:email,presence:true
    validates:content,presence:true
    
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :sender,foreign_key: :sender_id,class_name: 'User'
  belongs_to :recipient,foreign_key: :recipient_id,class_name: 'User'
  has_many :messages,dependent: :destroy
  validates_uniqueness_of :sender_id,scope: :recipient_id
  scope :between, ->(sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end


end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %I:%M %p")
  end


end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/poem.rb
class Poem < ActiveResource::Base
self.site = "https://frozen-cliffs-48094.herokuapp.com"
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
belongs_to :follower,class_name: "User"
belongs_to :followed,class_name: "User"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,:omniauthable

  has_many :blogs,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :relationships,foreign_key: "follower_id",dependent: :destroy
  has_many :reverse_relationships,foreign_key: "followed_id",class_name: "Relationship",dependent: :destroy
  has_many :followed_users,through: :relationships,source: :followed
  has_many :followers,through: :reverse_relationships,source: :follower

  mount_uploader :avatar,AvatarUploader

  def self.find_for_facebook_oauth(auth,signed_in_resource=nil)
    user=User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
      name: auth.extra.raw_info_.name,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||="#{auth.uid}-#{auth.provider}@example.com",
      image_url: auth.info.image,
      password: Devise.friendly_token[0,20]
      )
     user.skip_confirmation!
     user.save(validate: false)
   end
  user
end

def self.find_for_twitter_oauth(auth,signed_in_resource=nil)
  user = User.find_by(provider: auth.provider, uid: auth.uid)

  unless user
    user = User.new(
    name: auth.info.nickname,
    provider: auth.provider,
    uid: auth.uid,
    email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
    image_url: auth.info.image,
    password: Devise.friendly_token[0,20]
    )
    user.skip_confirmation!
    user.save(validate: false)
  end
  user
end

 def self.create_unique_string
   SecureRandom.uuid
 end

 def update_with_password(params,*options)
   if provider.blank?
     super
  else
    params.delete :current_password
    update_without_password(params,*options)
  end
 end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only:[:show,:edit,:update,:destroy]

  def index
    @users = User.all
    @blogs = Blog.all
    @blogs.order(created_at: :asc)
    #binding.pry
    #raise
  end

  def new
    if params[:back]
    @blog = Blog.new(blogs_params)
    else
    @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id=current_user.id
    @blog.user_name=current_user.name
    if @blog.save
    redirect_to blogs_path,notice:"ブログを作成しました!"
    NoticeMailer.sendmail_blog(@blog).deliver
    else
    render 'new'
    end
  end

  def edit
      @blog = Blog.find(params[:id])
  end

  def update
       @blog = Blog.find(params[:id])
       if @blog.update(blogs_params)
          redirect_to blogs_path,notice:"ブログを更新しました!"
       else
          render  'edit'
       end
  end

  def destroy
     @blog = Blog.find(params[:id])
     @blog.destroy
     redirect_to blogs_path,notice:"ブログを削除しました!"
  end

  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = @blog.comments.build
    @comments = @blog.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
  end


  private
   def blogs_params
     params.require(:blog).permit(:title,:content)
   end

   def set_blog
     @blog = Blog.find(params[:id])
   end

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

def index
 @poems = Poem.all
end

def show
@poem = Poem.find(params[:id])
end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def profile_img(user)
return image_tag(user.avatar, alt: user.name) if user.avatar.present?

  unless user.provider.blank?
   img_url = user.image_url
  else
   img_url = 'no_image.png'
  end
  image_tag(img_url, alt: user.name)
end

end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name =='new' || action_name =='confirm'
            confirm_blogs_path
        elsif action_name =='edit'
            blog_path
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
 <% if @blog.errors.any? %>
 <div id="error_explanation">
 <h2><%=@blog.errors.count %>件のエラーがあります。</h2>

 <ul>
 <% @blog.errors.full_messages.each do |msg| %>
 <li><%= msg %></li>
 <% end %>
 </ul>
 </div>
 <% end %>

 <%= f.label :title %>
 <%= f.text_field :title,class:'form-control' %>
 <br>
 <%= f.label :content %>
 <%= f.text_field :content,class:'form-control' %>
 <br>
 <%= f.submit'投稿',class:'btn btn-primary btn-block' %>
 <% end %>

 <%=link_to "ブログ一覧画面にもどる",blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h3>以下の内容で、送信する。</h3>
<%= form_for(@blog) do |f| %>

<%= f.hidden_field :title %>
<%= f.hidden_field :content %>
<p>タイトル:<%= @blog.title %></p>
<p>本文:<%= @blog.content %></p>
<%= f.submit"登録",class:'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@blog,url: new_blog_path,method:'get') do |f| %>
<%= f.hidden_field :title %>
<%= f.hidden_field :content %>
<%= f.submit"もどる",name: 'back',class:'btn btn-default btn-block' %>
<% end %>
</div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>ブログを編集する</h2>
<%= render 'form' %>
</div>
</div>

app/views/blogs/index.html.erb
<div class = container>
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
        <p><%=notice %></p>
        <h1>ブログ一覧</h1>
        <%= link_to "ブログを作成する",new_blog_path,class:'btn btn-default' %>

        <% @blogs.each do |blog| %>
        <div class="row">
        <%= profile_img(blog.user) if profile_img(blog.user) %>
        <%= link_to blog_path(blog) do %>
        <h4><strong><%= blog.title %></strong></h4>
        <% end %>
        <p><%=blog.content %></p>
        <p><%=blog.user.name %></p>
        <%=link_to"編集",edit_blog_path(blog.id),class:'btn btn-default btn-sm btn-success' %>
        <%=link_to"削除",blog_path(blog.id),method: :delete,data:{confirm:'本当に削除していいですか？'},class:'btn btn-default btn-sm btn btn-danger' %>
        </div>
        <% end %>
        </div>
        </div>

app/views/blogs/new.html.erb
<div class="container">
    <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>ブログを作成する</h2>
<%= render 'form' %>
</div>
</div>

app/views/blogs/show.html.erb
<p id = "notice"><%= notice %></p>
<div class = " child row">
  <div class= "wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class= "blog-text">
      <p class= "left"><strong>タイトル</strong></p>
      <p class="left"><%=@blog.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%=@blog.content %></p>
      <p class="right">
        <strong>作成時間:</strong>
        <%= @blog.created_at.strftime("%y/%m/%d %p %I:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <div id="comments_area">
      <%= render partial:'comments/index',locals:{comments:@comments,blog:@blog} %>
    </div>
    <%= render partial:'comments/form',locals:{comment:@comment,blog:@blog} %>
    <% if current_user.id == @blog.user_id %>
    <%= link_to '編集',edit_blog_path(@blog) %>
    <% end %>
    <%= link_to '戻る',blogs_path %>
  </div>
</div>

app/views/poems/index.html.erb
<%= @poems.each do |poem| %>
 <td>タイトル:<%=poem.title %></td>
 <td>content:<%=poem.content %></td>
 <td><%= link_to 'show',poem %></td><br />
 <% end %>

app/views/poems/show.html.erb
 <p>title:<%=@poem.title %></p>
 <p>content:<%=@poem.content %></p>