config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,controllers: {
    Registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :contacts, only:[:new,:create] do
   collection do
     post :confirm
   end
  end

  resources :blogs do
    resources :comments
      post :confirm,on: :collection
  end

  resources :users,only:[:index,:show]

  resources :relationships,only:[:create,:destroy]

  root 'top#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine,at:"/letter_opener"
  end

  resources :poems,only:[:index,:show]

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,:omniauthable

  has_many :blogs,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :relationships,foreign_key: "follower_id",dependent: :destroy
  has_many :reverse_relationships,foreign_key: "followed_id",class_name: "Relationship",dependent: :destroy
  has_many :followed_users,through: :relationships,source: :followed
  has_many :followers,through: :reverse_relationships,source: :follower

  mount_uploader :avatar,AvatarUploader

  def self.find_for_facebook_oauth(auth,signed_in_resource=nil)
    user=User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
      name: auth.extra.raw_info_.name,
      provider: auth.provider,
      uid: auth.uid,
      email: auth.info.email ||="#{auth.uid}-#{auth.provider}@example.com",
      image_url: auth.info.image,
      password: Devise.friendly_token[0,20]
      )
     user.skip_confirmation!
     user.save(validate: false)
   end
  user
end

def self.find_for_twitter_oauth(auth,signed_in_resource=nil)
  user = User.find_by(provider: auth.provider, uid: auth.uid)

  unless user
    user = User.new(
    name: auth.info.nickname,
    provider: auth.provider,
    uid: auth.uid,
    email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
    image_url: auth.info.image,
    password: Devise.friendly_token[0,20]
    )
    user.skip_confirmation!
    user.save(validate: false)
  end
  user
end

 def self.create_unique_string
   SecureRandom.uuid
 end

 def update_with_password(params,*options)
   if provider.blank?
     super
  else
    params.delete :current_password
    update_without_password(params,*options)
  end
 end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)

    if @user.persisted?
      set_flash_message(:notice,:success,kind: "Twitter")if is_navigational_format?
      sign_in_and_redirect @user, event: :authentivation
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  #ユーザーidをフォームから登録ではなく自動的に生成
  def build_resource(hash=nil)
    #ランダムなユーザーidを作成
    hash[:uid] = User.create_unique_string
    super
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user,only:[:show]

  def index
    @users = User.all
  end

  def show
    @users = User.all
  end

  private
   def set_user
     @user = User.find(params[:id])
   end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_follower_form.html.erb
<div class="col-md-2">
<%= profile_img(user) %>
<%= user.email %>
</div>

app/views/users/_follow_form.html.erb
  <div id="follow_form_<%=user.id %>">
    <% unless current_user.following?(user) %>
      <%= form_for(current_user.relationships.build(followed_id: user.id),remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー",class: "btn btn-large btn-primary" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.relationships.find_by(followed_id: user.id),html: {method: :delete},remote: true) do |f| %>
      <%= f.submit "つながりを解除",class: "btn btn-large" %>
      <% end %>
    <% end %>
  </div>

app/views/users/index.html.erb
  <h2>ユーザー一覧</h2>
  <% @users.each do |user| %>
  <div class="left">
    <div class="container-child col-md-2 col-md-offset-1 col-sm-4 col-xs-6 ">
  <%= link_to profile_img(user),user_path(user) %></br>
  <%= link_to user.email,user_path(user) %></br>
  <% if user.id != current_user.id %>
    <div class="item">
      <%= link_to user.name,user %>
      <%= link_to 'メッセージ',conversations_path(sender_id: current_user.id,recipient_id: user.id),method:'post'%>
    </div>
    <%= render partial:'follow_form',locals:{user: user} if signed_in? %>
  <% end %>
</div>
  <% end %>

app/views/users/show.html.erb
<div class= "container">
<% if @user.name == nil %>
<h2>ユーザー名不明の詳細画面</h2>
<% else %>
<h2><%= @user.name %>の詳細画面</h2>
<% end %>
<br>
<h3>フォローユーザー</h3>
<% @user.followed_users.each do |user| %>
 <%= render 'follow_follower_form',user: user %>
<% end %>
<br>
<br>
<br>
<br>
<h3><div class="follower">フォロワーユーザー</div></h3>
<% @user.followers.each do |user| %>
 <%= render 'follow_follower_form',user: user %>
<% end %>
</div>